#!/usr/bin/env node
var debug = require('debug')('epress-template');
var io = require('socket.io');
var app = require('./server');

app.set('port', process.env.PORT || 3000);
var server = app.listen(app.get('port'), function() {
    debug('Express server listening on port ' + server.address().port);
});

var servIO = io.listen(server);
servIO.sockets.on('connection', function (socket) {
    console.log('A new user connected!');
    socket.emit('info', { msg: 'The world is round, there is no up or down.' });
});
